### ISSUE TITLE
Screenshot only of visible viewport

### ISSUE THREAD

**Issue by jasondavis** [folletto/Blipshot#12]
Does this still work for full page screenshots?  Every-time I use the extension it snaps the first frame and shows it in the top right corner of screen and doesn't try to scroll or anything?

**Comment by folletto** [comment]
I just ran a few tests and it's still working. Chrome 48 on Mac.

Can you detail which version, operating system and page is having the issue you mention? :)

**Comment by folletto** [comment]
Closing due to no reply. Sorry!
