### ISSUE TITLE
Date & time format should be more like ISO 8601

### ISSUE THREAD

**Issue by oestrogen** [folletto/Blipshot#20]
`YYYY-MM-DD-HHMM'SS`, i.e, `2018-08-02-1016'36`, is a strange date and time format.

Preferably something like the ISO 8601 format (`YYYY-MM-DDTHH:MM:SS` i. e, `2018-08-28T10:39:01`) should be used. I would also be OK with `YYYY-MM-DD HH:MM:SS` i. e, `2018-08-28 10:39:01`, which is more readable.

**Comment by oestrogen** [comment]
With 2 years hindsight, this was a non-issue 😅.

**Comment by folletto** [comment]
I appreciate you coming back and replying to close it! Thanks! :)
