### ISSUE TITLE
Time stamp : only one per minute

### ISSUE THREAD

**Issue by Kweksma** [folletto/Blipshot#8]
Hi, 

I really like this add in. I want to use it several times a minute, but the timestamp is per minute. If I save multiple shots in one minute to one folder I can't because the file already exists.

 Is there a way to either
- use a serial timestamp (1,2,3)
- use the seconds in the timestamp

Thanks a lot!

**Comment by folletto** [comment]
Thanks! This was included in the 1.2 release :)

For reference, it was done in this commit: 18a620765ddeb32ba048f12eec09ff477311560c
